brain_extraction:
  docker:
    cmd: "docker run --gpus all <mount> thsanchez/fetpype_utils:latest run_brain_extraction 
      --input_stacks <input_stacks> 
      --output_masks <output_masks> 
      --method fet_bet"
  singularity:
    cmd: "singularity run --bind <singularity_mount> --nv
      <singularity_path>/fetpype_utils.sif
      run_brain_extraction
      --input_stacks <input_stacks> 
      --output_masks <output_masks> --method monaifbs"
  
check_stacks_and_masks:
  enabled: true

denoising:
  enabled: true
  docker:
    cmd: "docker run <mount> thsanchez/fetpype_utils:latest run_denoising 
      --input_stacks <input_stacks> 
      --output_stacks <output_stacks>"
  singularity:
    cmd: "singularity run --bind <singularity_mount>
      <singularity_path>/fetpype_utils.sif
      run_denoising
      --input_stacks <input_stacks> 
      --output_stacks <output_stacks>"
cropping:
  enabled: true
  
bias_correction:
  enabled: true
  docker:
    cmd: "docker run <mount> thsanchez/fetpype_utils:latest run_bias_field_correction 
      --input_stacks <input_stacks> 
      --input_masks <input_masks> 
      --output_stacks <output_stacks>"
  singularity:
    cmd: "singularity run --bind <singularity_mount>
      <singularity_path>/fetpype_utils.sif
      run_bias_field_correction
      --input_stacks <input_stacks> 
      --input_masks <input_masks> 
      --output_stacks <output_stacks>"