defaults:
  - preprocessing/default
  - reconstruction/nesvor
  - reconstruction/postprocessing
  - segmentation/fetalsynthseg
  - surface/surfpype
  - _self_
container: "docker"
reconstruction:
  output_resolution: 0.8
save_graph: True
