pipeline: "surface"
docker: 
  cmd: "docker run --rm <mount>
    fetpype/surf_proc:0.0.2a
    generate_mesh -l <labelling_scheme>
    -s <input_seg> 
    -m <output_surf>"
singularity:
  cmd: "singularity exec --bind <singularity_mount> --home <singularity_home> --nv
    <singularity_path>/surf_proc.sif
    generate_mesh -l <labelling_scheme>
    -s <input_seg> 
    -m <output_surf>"
use_scheme: "bounti"
out_file: "surf.stl"
labelling_scheme: 
  bounti: [5, 7, 14, 16]

